"""RAG-based KPI extraction (mirrors reference rag/kpi_extractor_rag.py).

Retrieve broad financial context for a company/year from the vector store, then
ask the LLM to return the KPIs as structured JSON.
"""
from __future__ import annotations

from pydantic import BaseModel, Field

from llm.gemini import get_structured_completion
from vectorstore.pgvector_store import Retriever


class FinancialMetrics(BaseModel):
    revenue: str | int | None = None
    net_income: str | int | None = None
    operating_income: str | int | None = None
    cash_flow: str | int | None = Field(
        None, description="Cash flow from operating activities"
    )
    total_assets: str | int | None = None
    total_liabilities: str | int | None = None
    risk_factors: list[str] | None = Field(None, description="Top risk factors")
    growth_drivers: list[str] | None = Field(None, description="Top growth drivers")


# Targeted retrieval queries: one per KPI group. Running several focused queries
# and merging the results reliably surfaces balance-sheet chunks (total assets /
# liabilities) that a single broad query often misses — while still feeding a
# single LLM call.
_RETRIEVAL_QUERIES = [
    "consolidated statements of operations revenue total net sales net income "
    "operating income",
    "consolidated statements of cash flows net cash provided by operating "
    "activities",
    "consolidated balance sheets total assets total liabilities "
    "stockholders equity",
    "risk factors that could materially affect the business",
    "management discussion growth drivers revenue growth performance",
]


# Exact statement line-labels for the lexical half of hybrid retrieval. These
# pull the number-heavy table chunks that vector search ranks poorly.
_KEYWORD_PHRASES = [
    "Total assets",
    "Total liabilities",
    "Net cash provided by operating activities",
    "Cash generated by operating activities",
    "Net income",
    "Total revenues",
    "Total net sales",
    "Operating income",
    "Income from operations",
]


def retrieve_context(
    retriever: Retriever,
    company: str,
    year: int | str | None,
    per_query_k: int = 5,
) -> str:
    """Hybrid retrieval: targeted vector queries + lexical statement-label lookup.

    Merges unique chunks from both so both narrative (risks/growth) and
    number-heavy statement tables (balance sheet) are in the LLM context.
    """
    seen: set[str] = set()
    ordered: list[str] = []

    def add(docs) -> None:
        for doc in docs:
            key = doc.page_content[:200]
            if key not in seen:
                seen.add(key)
                ordered.append(doc.page_content)

    for query in _RETRIEVAL_QUERIES:
        add(retriever.invoke(query=query, company=company, year=year, top_k=per_query_k))
    add(retriever.keyword_search(_KEYWORD_PHRASES, company=company, year=year))
    return "\n\n".join(ordered)


def build_prompt(company: str, year: int | str | None, context: str) -> str:
    return f"""
Company: {company}
Year: {year}

Context:
{context}

Extract the following into JSON with these exact keys:
- revenue
- net_income
- operating_income
- cash_flow            (cash flow from operating activities)
- total_assets
- total_liabilities
- risk_factors         (array of concise strings, top risks)
- growth_drivers       (array of concise strings, top growth drivers)

Rules:
- Use ONLY the provided context.
- Financial values must match the report exactly (keep currency/units).
- Financial statements usually show two fiscal years side by side. Always take
  the MOST RECENT year (fiscal year {year}), which is normally the right-hand
  column. e.g. "Total assets $ 450,256 $ 595,281" -> use 595,281.
- Use null when a value is not present in the context.
- Return valid JSON only, no commentary.
"""


def extract_financial_metrics(
    retriever: Retriever,
    company: str,
    year: int | str | None,
) -> dict:
    context = retrieve_context(retriever, company, year)
    prompt = build_prompt(company, year, context)
    metrics = get_structured_completion(prompt, FinancialMetrics)
    return metrics.model_dump()
